// <auto-generated />
using DragonGame.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DragonGame.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251029121824_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("DragonGame.Models.Act", b =>
                {
                    b.Property<int>("ActId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ActNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ActId");

                    b.HasIndex("StoryId");

                    b.ToTable("Acts", (string)null);

                    b.HasData(
                        new
                        {
                            ActId = 1,
                            ActNumber = 1,
                            StoryId = 1,
                            Text = "The dragon awakens..."
                        });
                });

            modelBuilder.Entity("DragonGame.Models.Choice", b =>
                {
                    b.Property<int>("ChoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("NextActNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ChoiceId");

                    b.HasIndex("ActId");

                    b.ToTable("Choices", (string)null);

                    b.HasData(
                        new
                        {
                            ChoiceId = 1,
                            ActId = 1,
                            NextActNumber = 2,
                            Text = "Go left"
                        },
                        new
                        {
                            ChoiceId = 2,
                            ActId = 1,
                            NextActNumber = 3,
                            Text = "Go right"
                        });
                });

            modelBuilder.Entity("DragonGame.Models.Story", b =>
                {
                    b.Property<int>("StoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("StoryId");

                    b.ToTable("Stories", (string)null);

                    b.HasData(
                        new
                        {
                            StoryId = 1,
                            Title = "Fallen Dragon"
                        });
                });

            modelBuilder.Entity("DragonGame.Models.Act", b =>
                {
                    b.HasOne("DragonGame.Models.Story", null)
                        .WithMany("Acts")
                        .HasForeignKey("StoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DragonGame.Models.Choice", b =>
                {
                    b.HasOne("DragonGame.Models.Act", "Act")
                        .WithMany("Choices")
                        .HasForeignKey("ActId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Act");
                });

            modelBuilder.Entity("DragonGame.Models.Act", b =>
                {
                    b.Navigation("Choices");
                });

            modelBuilder.Entity("DragonGame.Models.Story", b =>
                {
                    b.Navigation("Acts");
                });
#pragma warning restore 612, 618
        }
    }
}
