// <auto-generated />
using System;
using DragonGame.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DragonGame.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("DragonGame.Models.Act", b =>
                {
                    b.Property<int>("ActId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActNumber")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnding")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ActId");

                    b.HasIndex("StoryId");

                    b.ToTable("Acts", (string)null);

                    b.HasData(
                        new
                        {
                            ActId = 1,
                            ActNumber = 1,
                            IsEnding = false,
                            StoryId = 1,
                            Text = "The dragon awakens..."
                        });
                });

            modelBuilder.Entity("DragonGame.Models.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Face")
                        .HasColumnType("TEXT");

                    b.Property<string>("Hair")
                        .HasColumnType("TEXT");

                    b.Property<string>("Outfit")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PoseId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PoseId");

                    b.ToTable("Characters", (string)null);
                });

            modelBuilder.Entity("DragonGame.Models.CharacterPose", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CharacterPoses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "pose1.png",
                            Name = "Standing"
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "pose2.png",
                            Name = "Fighting"
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "pose3.png",
                            Name = "Flying"
                        });
                });

            modelBuilder.Entity("DragonGame.Models.Choice", b =>
                {
                    b.Property<int>("ChoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NextActNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ChoiceId");

                    b.HasIndex("ActId");

                    b.ToTable("Choices", (string)null);

                    b.HasData(
                        new
                        {
                            ChoiceId = 1,
                            ActId = 1,
                            NextActNumber = 2,
                            Text = "Go left"
                        },
                        new
                        {
                            ChoiceId = 2,
                            ActId = 1,
                            NextActNumber = 3,
                            Text = "Go right"
                        });
                });

            modelBuilder.Entity("DragonGame.Models.ChoiceHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChoiceId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("MadeAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlayerSessionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ChoiceId");

                    b.HasIndex("MadeAt");

                    b.HasIndex("PlayerSessionId");

                    b.ToTable("ChoiceHistories");
                });

            modelBuilder.Entity("DragonGame.Models.PlayerSession", b =>
                {
                    b.Property<int>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CharacterName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentActNumber")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StoryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SessionId");

                    b.HasIndex("CharacterId");

                    b.HasIndex("CurrentActNumber");

                    b.HasIndex("StoryId");

                    b.ToTable("PlayerSessions");
                });

            modelBuilder.Entity("DragonGame.Models.Story", b =>
                {
                    b.Property<int>("StoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("StoryId");

                    b.ToTable("Stories", (string)null);

                    b.HasData(
                        new
                        {
                            StoryId = 1,
                            Title = "Fallen Dragon"
                        });
                });

            modelBuilder.Entity("DragonGame.Models.Act", b =>
                {
                    b.HasOne("DragonGame.Models.Story", "Story")
                        .WithMany("Acts")
                        .HasForeignKey("StoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Story");
                });

            modelBuilder.Entity("DragonGame.Models.Character", b =>
                {
                    b.HasOne("DragonGame.Models.CharacterPose", "Pose")
                        .WithMany()
                        .HasForeignKey("PoseId");

                    b.Navigation("Pose");
                });

            modelBuilder.Entity("DragonGame.Models.Choice", b =>
                {
                    b.HasOne("DragonGame.Models.Act", "Act")
                        .WithMany("Choices")
                        .HasForeignKey("ActId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Act");
                });

            modelBuilder.Entity("DragonGame.Models.ChoiceHistory", b =>
                {
                    b.HasOne("DragonGame.Models.Choice", "Choice")
                        .WithMany()
                        .HasForeignKey("ChoiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DragonGame.Models.PlayerSession", "PlayerSession")
                        .WithMany("Choices")
                        .HasForeignKey("PlayerSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Choice");

                    b.Navigation("PlayerSession");
                });

            modelBuilder.Entity("DragonGame.Models.PlayerSession", b =>
                {
                    b.HasOne("DragonGame.Models.Character", "Character")
                        .WithMany("PlayerSessions")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DragonGame.Models.Act", "CurrentAct")
                        .WithMany()
                        .HasForeignKey("CurrentActNumber")
                        .HasPrincipalKey("ActNumber")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DragonGame.Models.Story", "Story")
                        .WithMany("PlayerSessions")
                        .HasForeignKey("StoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("CurrentAct");

                    b.Navigation("Story");
                });

            modelBuilder.Entity("DragonGame.Models.Act", b =>
                {
                    b.Navigation("Choices");
                });

            modelBuilder.Entity("DragonGame.Models.Character", b =>
                {
                    b.Navigation("PlayerSessions");
                });

            modelBuilder.Entity("DragonGame.Models.PlayerSession", b =>
                {
                    b.Navigation("Choices");
                });

            modelBuilder.Entity("DragonGame.Models.Story", b =>
                {
                    b.Navigation("Acts");

                    b.Navigation("PlayerSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
