// <auto-generated />
using DragonGame.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DragonGame.Data.Migrations
{
    [DbContext(typeof(DragonGameDbContext))]
    [Migration("20251015201820_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("DragonGame.Models.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Clothing")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Face")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Hair")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PoseId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PoseId");

                    b.ToTable("Characters", (string)null);
                });

            modelBuilder.Entity("DragonGame.Models.CharacterPose", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CharacterPoses", (string)null);
                });

            modelBuilder.Entity("DragonGame.Models.Character", b =>
                {
                    b.HasOne("DragonGame.Models.CharacterPose", "Pose")
                        .WithMany("Characters")
                        .HasForeignKey("PoseId");

                    b.Navigation("Pose");
                });

            modelBuilder.Entity("DragonGame.Models.CharacterPose", b =>
                {
                    b.Navigation("Characters");
                });
#pragma warning restore 612, 618
        }
    }
}
