// <auto-generated />
using DragonGame.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DragonGame.Data.Migrations
{
    [DbContext(typeof(DragonGameDbContext))]
    partial class DragonGameDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("DragonGame.Models.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Clothing")
                        .HasColumnType("TEXT");

                    b.Property<string>("Face")
                        .HasColumnType("TEXT");

                    b.Property<string>("Hair")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PoseId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PoseId");

                    b.ToTable("Characters", (string)null);
                });

            modelBuilder.Entity("DragonGame.Models.CharacterPose", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CharacterPoses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "pose1.png",
                            Name = "Standing"
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "pose2.png",
                            Name = "Fighting"
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "pose3.png",
                            Name = "Flying"
                        });
                });

            modelBuilder.Entity("DragonGame.Models.Character", b =>
                {
                    b.HasOne("DragonGame.Models.CharacterPose", "Pose")
                        .WithMany()
                        .HasForeignKey("PoseId");

                    b.Navigation("Pose");
                });
#pragma warning restore 612, 618
        }
    }
}
